import { describe, expect, it } from 'vitest'
import { generateQuiz, inferSchema, parseCsv } from './quizGenerator'
import { isBlitzEligible } from './blitz'
import { parseQuiz } from './quizValidation'
import { preloadAnswerImages } from './preload'

const flag = (name: string) => `https://example.org/flags/${name}.svg`
const rows = parseCsv([
  'pays;article;capitale;drapeau',
  `Cuba;;La Havane;${flag('cuba')}`,
  `Haïti;;Port-au-Prince;${flag('haiti')}`,
  `Jamaïque;la;Kingston;${flag('jamaica')}`,
  `Barbade;la;Bridgetown;${flag('barbados')}`,
  `Bahamas;les;Nassau;${flag('bahamas')}`,
  `Belize;;Belmopan;${flag('belize')}`,
].join('\n'))
const schema = { ...inferSchema(rows), noun: 'territoire', title: 'Test' }
const shapes = Object.fromEntries(rows.map((r) => [r.pays, `<svg viewBox="0 0 1 1"><path d="M0 0h1v1z" data-of="${r.pays}"/></svg>`]))

const hasVisualAnswers = (q: { type: string; content?: unknown }): boolean =>
  q.type === 'qcm' && (q as { content: { answers: { imageUrl?: string; shapeSvg?: string }[] } }).content.answers.some((a) => a.imageUrl || a.shapeSvg)

const inverse = (quiz: ReturnType<typeof generateQuiz>) => quiz.questions.filter(hasVisualAnswers)

describe('inverse questions (image answers), blitz only', () => {
  it('are not generated by default', () => {
    expect(inverse(generateQuiz(rows, schema, { seed: 's', shapes }))).toHaveLength(0)
  })

  it('give 4 image answers with exactly one correct, all playable in the blitz', () => {
    const quiz = generateQuiz(rows, schema, { seed: 's', shapes, choices: 4, inverse: true })
    const flags = inverse(quiz).filter((q) => q.type === 'qcm' && q.content.answers.every((a) => a.imageUrl))
    const outlines = inverse(quiz).filter((q) => q.type === 'qcm' && q.content.answers.every((a) => a.shapeSvg))
    expect(flags).toHaveLength(rows.length)
    expect(outlines).toHaveLength(rows.length)
    for (const q of [...flags, ...outlines]) {
      if (q.type !== 'qcm') continue
      expect(isBlitzEligible(q)).toBe(true)
      expect(q.content.answers.filter((a) => a.isCorrect)).toHaveLength(1)
      expect(new Set(q.content.answers.map((a) => a.label)).size).toBe(4)
      expect(q.imageUrl).toBeUndefined()
      expect(q.shapeSvg).toBeUndefined()
    }
  })

  it('show the right picture in the correct square, and name it in the label', () => {
    const quiz = generateQuiz(rows, schema, { seed: 's', shapes, choices: 4, inverse: true })
    const cuba = inverse(quiz).find((q) => q.type === 'qcm' && q.subject === 'Cuba' && q.content.answers.every((a) => a.imageUrl))
    if (!cuba || cuba.type !== 'qcm') throw new Error('question inverse de Cuba introuvable')
    expect(cuba.question).toBe('Drapeau de Cuba ?')
    const correct = cuba.content.answers.find((a) => a.isCorrect)!
    expect(correct.label).toBe('Cuba')
    expect(correct.imageUrl).toBe(flag('cuba'))
    const outline = inverse(quiz).find((q) => q.type === 'qcm' && q.subject === 'Cuba' && q.content.answers.every((a) => a.shapeSvg))
    if (!outline || outline.type !== 'qcm') throw new Error('silhouette inverse de Cuba introuvable')
    expect(outline.question).toBe('Silhouette de Cuba ?')
    expect(outline.content.answers.find((a) => a.isCorrect)!.shapeSvg).toContain('data-of="Cuba"')
  })

  it('survive quiz validation with their image answers', () => {
    const quiz = parseQuiz(generateQuiz(rows, schema, { seed: 's', shapes, choices: 4, inverse: true }))
    expect(inverse(quiz).length).toBeGreaterThan(0)
  })

  it('do not change the direct questions that exist without them', () => {
    const ids = (withInverse: boolean) => generateQuiz(rows, schema, { seed: 's', shapes, choices: 4, inverse: withInverse }).questions
      .filter((q) => !hasVisualAnswers(q)).map((q) => q.id).sort()
    expect(ids(true)).toEqual(ids(false))
  })
})

describe('preloadAnswerImages', () => {
  it('resolves immediately without image answers or outside a browser', async () => {
    const quiz = generateQuiz(rows, schema, { seed: 's', shapes })
    await expect(preloadAnswerImages(quiz.questions[0])).resolves.toBeUndefined()
    await expect(preloadAnswerImages(undefined)).resolves.toBeUndefined()
    const withFlags = inverse(generateQuiz(rows, schema, { seed: 's', shapes, choices: 4, inverse: true }))[0]
    await expect(preloadAnswerImages(withFlags)).resolves.toBeUndefined()
  })
})
